version: '3.5'
services:
  ngx-admin-prod:
    container_name: ngx-admin-prod
    build:
      context: .
      dockerfile: Dockerfile-prod
    ports:
      - '80:80'
    environment:
      - CHOKIDAR_USEPOLLING=true